// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuMjLLim50rloZ4XzY1D-RfDO1w_Dyyp8',
    appId: '1:474161802737:ios:e4f1d10556fab71d1aa850',
    messagingSenderId: '474161802737',
    projectId: 'assosc-98fb3',
    storageBucket: 'assosc-98fb3.appspot.com',
    iosBundleId: 'com.example.assosc',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPLAIrnD_Fn8hXvJCFsy2RbzCOIeX5YcQ',
    appId: '1:474161802737:android:b264f9f2700ab8b91aa850',
    messagingSenderId: '474161802737',
    projectId: 'assosc-98fb3',
    storageBucket: 'assosc-98fb3.appspot.com',
  );

}